import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { NodeIO } from '@gltf-transform/core';
import { KHRDracoMeshCompression } from '@gltf-transform/extensions';
import { draco } from '@gltf-transform/functions';
import draco3d from 'draco3d';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const [variant,png]=process.argv.slice(2);
if(!['cab','intermediate'].includes(variant)||!png)throw new Error('Usage: node scripts/retexture.mjs cab|intermediate edited-1024.png');
const data=await fs.readFile(path.resolve(png)),meta=await sharp(data).metadata();
if(meta.width!==1024||meta.height!==1024||meta.format!=='png')throw new Error('Texture must be a 1024×1024 PNG');
const io=new NodeIO().registerExtensions([KHRDracoMeshCompression]).registerDependencies({'draco3d.decoder':await draco3d.createDecoderModule(),'draco3d.encoder':await draco3d.createEncoderModule()});
const file=path.join(root,'assets',`c151-${variant}.glb`),doc=await io.read(file);
doc.getRoot().listTextures()[0].setImage(data).setMimeType('image/png');
await doc.transform(draco({method:'edgebreaker',encodeSpeed:5,decodeSpeed:5,quantizePosition:16,quantizeNormal:10,quantizeTexcoord:14}));
const dest=path.join(root,'assets',`c151-${variant}-retextured.glb`);
await io.write(dest,doc);console.log(dest);
